"""
Email Alert Module for Phishing Detection
Sends email notifications when phishing is detected
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import logging
from datetime import datetime
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

# SMTP Configuration from Environment Variables
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USERNAME = os.getenv("SMTP_USERNAME", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
ALERT_RECIPIENTS = os.getenv("ALERT_RECIPIENTS", "").split(",")


def send_phishing_alert(
    email_content: str,
    risk_score: float,
    action: str,
    sender: str = None,
    subject: str = None,
    matched_patterns: List[str] = None
) -> bool:
    """
    Send an email alert when phishing is detected
    
    Args:
        email_content: The suspicious email content
        risk_score: Risk score from ML model (0-1)
        action: Action taken (BLOCK/QUARANTINE/ALLOW)
        sender: Original email sender
        subject: Original email subject
        matched_patterns: List of patterns that triggered detection
    
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    if not SMTP_USERNAME or not SMTP_PASSWORD:
        logger.warning("Email credentials not configured. Skipping alert.")
        return False
    
    if not ALERT_RECIPIENTS or ALERT_RECIPIENTS == ['']:
        logger.warning("No alert recipients configured. Skipping alert.")
        return False
    
    # Only send alerts for high-risk emails
    if risk_score < 0.7:
        logger.info(f"Risk score {risk_score:.2%} below threshold. No alert sent.")
        return False
    
    # Build email content
    severity = "🔴 CRITICAL" if risk_score > 0.85 else "🟠 HIGH"
    
    html_body = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; }}
            .header {{ background-color: #c62828; color: white; padding: 15px; border-radius: 5px; }}
            .risk-high {{ color: #c62828; font-weight: bold; font-size: 18px; }}
            .info {{ background-color: #f5f5f5; padding: 10px; margin: 10px 0; border-radius: 5px; }}
            .details {{ font-family: monospace; white-space: pre-wrap; background-color: #fafafa; padding: 10px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h2>{severity} Phishing Threat Detected!</h2>
        </div>
        
        <div class="info">
            <p><strong>🛡️ Confidence Score:</strong> <span class="risk-high">{risk_score:.1%}</span></p>
            <p><strong>🚨 Action Taken:</strong> {action}</p>
            <p><strong>📅 Detection Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        </div>
        
        <div class="info">
            <h3>📧 Original Email Details:</h3>
            <p><strong>From:</strong> {sender or 'Unknown'}</p>
            <p><strong>Subject:</strong> {subject or 'No subject'}</p>
        </div>
    """
    
    if matched_patterns:
        html_body += f"""
        <div class="info">
            <h3>🎯 Detection Patterns:</h3>
            <ul>
                {"".join(f'<li>{pattern}</li>' for pattern in matched_patterns[:5])}
            </ul>
        </div>
        """
    
    html_body += f"""
        <div class="info">
            <h3>📝 Suspicious Email Content:</h3>
            <div class="details">{email_content[:500]}{'...' if len(email_content) > 500 else ''}</div>
        </div>
        
        <div class="info">
            <h3>⚠️ Recommended Actions:</h3>
            <ul>
                <li>Do NOT click any links in this email</li>
                <li>Do NOT reply or forward to others</li>
                <li>Block the sender domain in your email gateway</li>
                <li>Investigate if any credentials were recently shared</li>
            </ul>
        </div>
        
        <hr>
        <p><small>Generated by AI-Powered Phishing Detection System | MLOps + DevSecOps Pipeline</small></p>
    </body>
    </html>
    """
    
    plain_body = f"""
    {'🔴 CRITICAL' if risk_score > 0.85 else '🟠 HIGH'} PHISHING THREAT DETECTED!
    
    Confidence Score: {risk_score:.1%}
    Action Taken: {action}
    Detection Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}
    
    Original Email:
    From: {sender or 'Unknown'}
    Subject: {subject or 'No subject'}
    
    Suspicious Content:
    {email_content[:500]}
    
    Recommended Actions:
    - Do NOT click any links in this email
    - Block the sender domain
    - Investigate for credential exposure
    
    ---
    AI-Powered Phishing Detection System
    """
    
    try:
        # Create message
        msg = MIMEMultipart('alternative')
        msg['From'] = SMTP_USERNAME
        msg['To'] = ', '.join(ALERT_RECIPIENTS)
        msg['Subject'] = f"[PHISHING ALERT] {severity} - {risk_score:.0%} confidence"
        
        # Attach both plain text and HTML versions
        msg.attach(MIMEText(plain_body, 'plain'))
        msg.attach(MIMEText(html_body, 'html'))
        
        # Send email
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(SMTP_USERNAME, ALERT_RECIPIENTS, msg.as_string())
        
        logger.info(f"✅ Phishing alert sent to {len(ALERT_RECIPIENTS)} recipient(s)")
        return True
        
    except Exception as e:
        logger.error(f"❌ Failed to send email alert: {str(e)}")
        return False


def send_test_alert() -> bool:
    """Send a test email to verify configuration"""
    return send_phishing_alert(
        email_content="This is a test email to verify your phishing detection alert system is working correctly.",
        risk_score=0.95,
        action="TEST",
        sender="test@system.com",
        subject="Test Alert - Phishing Detection System",
        matched_patterns=["Test pattern"]
    )