"""
DevSecOps + AI: Real-time Phishing Detection with Enforcement
MLOps Feedback Loop + Automated Security Gates
"""
from fastapi import FastAPI, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from pydantic import BaseModel, Field
from datetime import datetime
import joblib
import logging
import json
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional, List
from contextlib import asynccontextmanager

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ============================================================
# EMAIL ALERT FUNCTION
# ============================================================
def send_phishing_alert(
    email_content: str,
    risk_score: float,
    action: str,
    sender: str = None,
    subject: str = None,
    matched_patterns: List[str] = None
) -> bool:
    """
    Send an email alert when phishing is detected
    """
    # Get configuration from environment variables
    smtp_server = os.getenv("SMTP_SERVER", "")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_username = os.getenv("SMTP_USERNAME", "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")
    alert_recipients = os.getenv("ALERT_RECIPIENTS", "").split(",")

    if not smtp_username or not smtp_password:
        logger.warning("Email credentials not configured. Skipping alert.")
        return False

    if not alert_recipients or alert_recipients == ['']:
        logger.warning("No alert recipients configured. Skipping alert.")
        return False

    # Only send alerts for high-risk emails
    if risk_score < 0.7:
        logger.info(f"Risk score {risk_score:.2%} below threshold. No alert sent.")
        return False

    severity = "🔴 CRITICAL" if risk_score > 0.85 else "🟠 HIGH"

    # HTML email body
    html_body = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; }}
            .header {{ background-color: #c62828; color: white; padding: 15px; border-radius: 5px; }}
            .risk-high {{ color: #c62828; font-weight: bold; font-size: 18px; }}
            .info {{ background-color: #f5f5f5; padding: 10px; margin: 10px 0; border-radius: 5px; }}
            .details {{ font-family: monospace; white-space: pre-wrap; background-color: #fafafa; padding: 10px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h2>{severity} Phishing Threat Detected!</h2>
        </div>

        <div class="info">
            <p><strong>🛡️ Confidence Score:</strong> <span class="risk-high">{risk_score:.1%}</span></p>
            <p><strong>🚨 Action Taken:</strong> {action}</p>
            <p><strong>📅 Detection Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        </div>

        <div class="info">
            <h3>📧 Original Email Details:</h3>
            <p><strong>From:</strong> {sender or 'Unknown'}</p>
            <p><strong>Subject:</strong> {subject or 'No subject'}</p>
        </div>
    """

    if matched_patterns:
        html_body += f"""
        <div class="info">
            <h3>🎯 Detection Patterns:</h3>
            <ul>
                {"".join(f'<li>{pattern}</li>' for pattern in matched_patterns[:5])}
            </ul>
        </div>
        """

    html_body += f"""
        <div class="info">
            <h3>📝 Suspicious Email Content:</h3>
            <div class="details">{email_content[:500]}{'...' if len(email_content) > 500 else ''}</div>
        </div>

        <div class="info">
            <h3>⚠️ Recommended Actions:</h3>
            <ul>
                <li>Do NOT click any links in this email</li>
                <li>Do NOT reply or forward to others</li>
                <li>Block the sender domain in your email gateway</li>
                <li>Investigate if any credentials were recently shared</li>
            </ul>
        </div>

        <hr>
        <p><small>Generated by AI-Powered Phishing Detection System | MLOps + DevSecOps Pipeline</small></p>
    </body>
    </html>
    """

    plain_body = f"""
    {severity} PHISHING THREAT DETECTED!

    Confidence Score: {risk_score:.1%}
    Action Taken: {action}
    Detection Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

    Original Email:
    From: {sender or 'Unknown'}
    Subject: {subject or 'No subject'}

    Suspicious Content:
    {email_content[:500]}

    Recommended Actions:
    - Do NOT click any links in this email
    - Block the sender domain
    - Investigate for credential exposure

    ---
    AI-Powered Phishing Detection System
    """

    try:
        msg = MIMEMultipart('alternative')
        msg['From'] = smtp_username
        msg['To'] = ', '.join(alert_recipients)
        msg['Subject'] = f"[PHISHING ALERT] {severity} - {risk_score:.0%} confidence"

        msg.attach(MIMEText(plain_body, 'plain'))
        msg.attach(MIMEText(html_body, 'html'))

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_username, smtp_password)
            server.sendmail(smtp_username, alert_recipients, msg.as_string())

        logger.info(f"✅ Phishing alert sent to {len(alert_recipients)} recipient(s)")
        return True

    except Exception as e:
        logger.error(f"❌ Failed to send email alert: {str(e)}")
        return False


# ============================================================
# FEEDBACK LOGGING FUNCTION
# ============================================================
FEEDBACK_FILE = "feedback_log.json"


def log_incident(email_content: str, risk_score: float, action: str, is_correct: bool = None):
    """Log security incidents for feedback loop and SIEM"""
    incident = {
        "timestamp": datetime.utcnow().isoformat(),
        "email_content": email_content[:500],
        "risk_score": risk_score,
        "action": action,
        "confirmed_phishing": is_correct
    }

    try:
        with open(FEEDBACK_FILE, "a") as f:
            f.write(json.dumps(incident) + "\n")
        logger.info(f"📝 Incident logged: {action} - Risk: {risk_score:.2%}")
    except Exception as e:
        logger.error(f"Failed to log incident: {e}")


# ============================================================
# FASTAPI APPLICATION
# ============================================================
app = FastAPI(
    title="AI Phishing Detection API",
    description="MLOps + DevSecOps: Automated security enforcement with email alerts",
    version="2.0.0"
)

app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=["*.azurewebsites.net", "*.azurecontainerapps.io", "localhost", "127.0.0.1", "*"]
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================================
# LOAD MODEL
# ============================================================
MODEL_PATH = os.getenv("MODEL_PATH", "model/phishing_model.pkl")
VECTORIZER_PATH = os.getenv("VECTORIZER_PATH", "model/vectorizer.pkl")
METADATA_PATH = os.getenv("METADATA_PATH", "model/metadata.json")

model = None
vectorizer = None
model_metadata = {'model_version': 'unknown', 'accuracy': 0}

try:
    if os.path.exists(MODEL_PATH) and os.path.exists(VECTORIZER_PATH):
        model = joblib.load(MODEL_PATH)
        vectorizer = joblib.load(VECTORIZER_PATH)
        if os.path.exists(METADATA_PATH):
            with open(METADATA_PATH, 'r') as f:
                model_metadata = json.load(f)
        logger.info(f"✅ Model loaded - Version: {model_metadata.get('model_version', 'unknown')}")
    else:
        logger.warning(f"⚠️ Model files not found at {MODEL_PATH}")
except Exception as e:
    logger.error(f"❌ Failed to load model: {e}")


# ============================================================
# REQUEST/RESPONSE MODELS
# ============================================================
class EmailScanRequest(BaseModel):
    email_content: str = Field(..., min_length=1, max_length=5000)
    sender: Optional[str] = None
    subject: Optional[str] = None


class ScanResponse(BaseModel):
    risk_score: float
    is_phishing: bool
    confidence: float
    action: str
    model_version: str
    timestamp: str
    alert_sent: bool = False


# ============================================================
# PHISHING KEYWORDS FOR FALLBACK DETECTION
# ============================================================
PHISHING_KEYWORDS = [
    'verify', 'click here', 'urgent', 'compromised', 'suspended',
    'unusual login', 'congratulations', 'invoice', 'past due',
    'expire', 'payment', 'limited', 'blocked', 'password reset',
    'account verification', 'security alert', 'immediate action'
]


def get_matched_patterns(email_content: str) -> List[str]:
    """Return list of phishing patterns found in email"""
    email_lower = email_content.lower()
    return [p for p in PHISHING_KEYWORDS if p in email_lower]


# ============================================================
# SCAN ENDPOINT
# ============================================================
@app.post("/scan", response_model=ScanResponse)
async def scan_email(request: EmailScanRequest, background_tasks: BackgroundTasks):
    """
    AI-powered scan with automatic enforcement (DevSecOps gate)
    Sends email alerts for high-risk detections
    """
    logger.info(f"📧 Scanning email from: {request.sender or 'unknown'}")

    # Get matched patterns for alert
    matched_patterns = get_matched_patterns(request.email_content)

    if model is None or vectorizer is None:
        # Fallback rule-based detection
        email_lower = request.email_content.lower()
        risk_score = sum(0.12 for p in PHISHING_KEYWORDS if p in email_lower)
        risk_score = min(risk_score, 1.0)
        logger.info("Using fallback rule-based detection")
    else:
        # ML-based detection
        email_vector = vectorizer.transform([request.email_content])
        proba = model.predict_proba(email_vector)[0]
        risk_score = float(proba[1])

    confidence = abs(risk_score - 0.5) * 2

    # DevSecOps: Enforce Security Policy
    if risk_score > 0.75:
        action = "BLOCK"
        logger.warning(f"🚨 BLOCKED: High-risk email (score: {risk_score:.2%})")
        background_tasks.add_task(log_incident, request.email_content, risk_score, action)

        # Send email alert for high-risk detections
        background_tasks.add_task(
            send_phishing_alert,
            email_content=request.email_content,
            risk_score=risk_score,
            action=action,
            sender=request.sender,
            subject=request.subject,
            matched_patterns=matched_patterns
        )
        alert_sent = True

    elif risk_score > 0.5:
        action = "QUARANTINE"
        logger.warning(f"⚠️ QUARANTINED: Suspicious email (score: {risk_score:.2%})")
        background_tasks.add_task(log_incident, request.email_content, risk_score, action)

        # Send alert for quarantine as well (medium-high risk)
        if risk_score > 0.65:
            background_tasks.add_task(
                send_phishing_alert,
                email_content=request.email_content,
                risk_score=risk_score,
                action=action,
                sender=request.sender,
                subject=request.subject,
                matched_patterns=matched_patterns
            )
            alert_sent = True
        else:
            alert_sent = False

    else:
        action = "ALLOW"
        logger.info(f"✅ ALLOWED: Safe email (score: {risk_score:.2%})")
        alert_sent = False

    return ScanResponse(
        risk_score=risk_score,
        is_phishing=risk_score > 0.5,
        confidence=confidence,
        action=action,
        model_version=model_metadata.get('model_version', '1.0.0'),
        timestamp=datetime.utcnow().isoformat(),
        alert_sent=alert_sent
    )


# ============================================================
# FEEDBACK ENDPOINT (MLOps Loop)
# ============================================================
@app.post("/feedback")
async def provide_feedback(email_content: str, was_correct: bool):
    """
    MLOps Feedback Loop: Security team confirms if detection was correct
    """
    logger.info(f"📝 Feedback received: {'Correct' if was_correct else 'Incorrect'} detection")

    try:
        if not os.path.exists(FEEDBACK_FILE):
            return {"status": "error", "message": "No incidents found"}

        with open(FEEDBACK_FILE, "r") as f:
            lines = f.readlines()

        updated = False
        for i in range(len(lines) - 1, -1, -1):
            data = json.loads(lines[i])
            if data['email_content'] == email_content:
                if data['risk_score'] > 0.5:
                    data['confirmed_phishing'] = was_correct
                else:
                    data['confirmed_phishing'] = not was_correct
                lines[i] = json.dumps(data) + "\n"
                updated = True
                break

        if updated:
            with open(FEEDBACK_FILE, "w") as f:
                f.writelines(lines)

            sample_count = len(lines)
            if sample_count >= 50:
                logger.warning(f"🎯 {sample_count} samples collected! Ready for model retraining")
                return {"status": "feedback recorded", "will_trigger_retraining": True, "samples": sample_count}

            return {"status": "feedback recorded", "will_trigger_retraining": False, "samples": sample_count}
        else:
            return {"status": "error", "message": "Email not found in logs"}

    except Exception as e:
        logger.error(f"Feedback error: {e}")
        return {"status": "error", "message": str(e)}


# ============================================================
# TEST ALERT ENDPOINT
# ============================================================
@app.post("/test-alert")
async def test_alert():
    """
    Send a test email to verify alert configuration
    """
    success = send_phishing_alert(
        email_content="This is a test email to verify your phishing detection alert system.",
        risk_score=0.95,
        action="TEST",
        sender="test@phish-detector.com",
        subject="Test Alert - Phishing Detection System",
        matched_patterns=["test pattern", "verification"]
    )
    return {"alert_sent": success, "message": "Test alert sent successfully" if success else "Failed to send alert"}


# ============================================================
# METRICS ENDPOINT
# ============================================================
@app.get("/metrics")
async def get_metrics():
    """MLOps: Model performance metrics"""
    metrics = {
        "model_version": model_metadata.get('model_version', '1.0.0'),
        "accuracy": model_metadata.get('accuracy', 0.75),
        "training_samples": model_metadata.get('training_samples', 0),
        "status": "healthy" if model is not None else "degraded_fallback",
        "alert_configured": bool(os.getenv("SMTP_USERNAME"))
    }

    if os.path.exists(FEEDBACK_FILE):
        try:
            with open(FEEDBACK_FILE, "r") as f:
                logs = [json.loads(line) for line in f]

            total = len(logs)
            blocked = sum(1 for log in logs if log.get('action') == 'BLOCK')

            metrics['total_scans'] = total
            metrics['blocked_count'] = blocked
            metrics['block_rate'] = round(blocked / total * 100, 2) if total > 0 else 0
            metrics['feedback_samples'] = total
        except Exception:
            pass

    return metrics


# ============================================================
# HEALTH CHECK ENDPOINT
# ============================================================
@app.get("/health")
async def health_check():
    """Health check for container orchestration"""
    return {
        "status": "healthy",
        "model_loaded": model is not None,
        "model_version": model_metadata.get('model_version', 'unknown'),
        "alert_configured": bool(os.getenv("SMTP_USERNAME")),
        "timestamp": datetime.utcnow().isoformat()
    }


# ============================================================
# ROOT ENDPOINT
# ============================================================
@app.get("/")
async def root():
    """Root endpoint with API info"""
    return {
        "service": "AI Phishing Detection API",
        "version": "2.0.0",
        "description": "MLOps + DevSecOps: Automated security enforcement with email alerts",
        "status": "running",
        "endpoints": [
            "/scan - POST (scan email)",
            "/feedback - POST (provide feedback for retraining)",
            "/test-alert - POST (test email alerts)",
            "/metrics - GET (view model metrics)",
            "/health - GET (health check)",
            "/docs - GET (Swagger documentation)"
        ]
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)